# Generated by Django 6.0.1 on 2026-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
