# Generated by Django 6.0.1 on 2026-01-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='is_active',
        ),
    ]
