# Generated by Django 6.0.1 on 2026-01-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('equipment', models.CharField(max_length=100, verbose_name='Equipment')),
                ('trailer_type', models.CharField(max_length=100, verbose_name='Trailer Type')),
                ('commodity', models.CharField(max_length=255, verbose_name='Commodity')),
                ('weight', models.CharField(max_length=100, verbose_name='Weight')),
                ('description', models.TextField(verbose_name='Description')),
                ('pickup_zip_code', models.CharField(max_length=20, verbose_name='Pickup Zip')),
                ('pickup_date', models.DateField(verbose_name='Pickup Date')),
                ('delivery_zip_code', models.CharField(max_length=20, verbose_name='Delivery Zip')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freight Quote',
                'verbose_name_plural': 'Freight Quotes',
            },
        ),
    ]
