# Generated by Django 6.0.1 on 2026-01-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_messages', '0002_freightquote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freightquote',
            old_name='delivery_date',
            new_name='dropoff_date',
        ),
        migrations.RenameField(
            model_name='freightquote',
            old_name='delivery_zip_code',
            new_name='dropoff_zip_code',
        ),
    ]
