# Generated by Django 6.0.1 on 2026-01-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
    ]

    operations = [
    ]
