from django.conf import settings
from django.core.mail import send_mail
from django.utils.html import strip_tags


def send_freight_email(instance):
    """
    FreightQuote obyektidan ma'lumot olib, admin pochtasiga yuboradi.
    """
    subject = f"🚚 New Freight Quote: {instance.commodity} from {instance.full_name}"

    # HTML formatidagi xat dizayni
    html_message = f"""
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; max-width: 600px; border: 1px solid #eee; padding: 20px;">
        <h2 style="color: #004a99; border-bottom: 2px solid #004a99; padding-bottom: 10px;">BMTransco - New Quote Request</h2>
        <p>You have received a new freight quote request with the following details:</p>

        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Customer Name</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{instance.full_name}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Email / Phone</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{instance.email} / {instance.phone}</td>
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Company</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{instance.company or "N/A"}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Equipment / Trailer</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{instance.equipment} / {instance.trailer_type}</td>
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Commodity (Weight)</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{instance.commodity} ({instance.weight})</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Pickup</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">Zip: {instance.pickup_zip_code} | Date: {instance.pickup_date}</td>
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Delivery</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">Zip: {instance.delivery_zip_code} | Date: {instance.delivery_date}</td>
            </tr>
        </table>

        <div style="margin-top: 20px; padding: 10px; background-color: #fff8e1; border-left: 4px solid #ffc107;">
            <strong>Message/Description:</strong><br>
            {instance.description}
        </div>

        <p style="font-size: 12px; color: #777; margin-top: 30px;">
            This email was automatically generated by BMTransco System.
        </p>
    </div>
    """

    plain_message = strip_tags(html_message)

    return send_mail(
        subject=subject,
        message=plain_message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[settings.ADMIN_EMAIL],
        html_message=html_message,
        fail_silently=False,
    )
