# Generated by Django 5.2.7 on 2025-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
