# Generated by Django 6.0.1 on 2026-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
