# Generated by Django 6.0.1 on 2026-01-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_homepage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
